[package]
name = "text_editor"
version = "0.1.0"
edition = "2024"


[dependencies]
eframe = "0.32.3"
egui = "0.32.3"
egui-phosphor = "0.10.0"
egui_code_editor = "0.2.17"
rfd = "0.15.4"
syntect = "5.2.0"



